const constant = {};
constant.DOCTORS_DATA_FETCH_SUCCESS = 'DOCTORS_DATA_FETCH_SUCCESS';
constant.SERVICES_DATA_FETCH_SUCCESS = 'SERVICES_DATA_FETCH_SUCCESS';
constant.TOGGLE_DOCTORS_LOADER = 'TOGGLE_DOCTORS_LOADER';
constant.TOGGLE_SERVICE_LOADER = 'TOGGLE_SERVICE_LOADER';
export default constant;
